### ISSUE TITLE
صفحه نمایش جزئیات اطلاعات هر بازیگر

### ISSUE THREAD

**Issue by rezaiyan** [dovahcin/Movie#34]
دریافت جزئیات:
https://developers.themoviedb.org/3/people/get-person-details

لیست عکس‌ها:
https://developers.themoviedb.org/3/people/get-person-images

نمایش لیست افقی فیلم‌های این بازیگر:
https://developers.themoviedb.org/3/discover/movie-discover
`https://api.themoviedb.org/3/discover/movie?with_people={id}`

طراحی:

<img src="https://user-images.githubusercontent.com/16861750/131218505-6f6e5dab-dec4-41ce-b1ee-4533320de098.png" width="30%"/>
<img src="https://user-images.githubusercontent.com/16861750/131218534-43d4b463-bda4-49a8-96f8-7235511a464c.png" width="30%"/>

**Comment by dovahcin** [comment]
به نظرم اولی بیشتر با یوآی بعدی اپ سازگاره
